//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuppetShow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class MuppetsTable
    {
        public int Id { get; set; }
        [Display(Name = "Character Name")]
        public string name { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "First Appearance")]
        public Nullable<System.DateTime> firstAppearance { get; set; }
        [Display(Name = "Image")]
        public string image { get; set; }
        [Display(Name = "Video")]
        public string video { get; set; }
        [Display(Name = "Likes")]
        public Nullable<int> likes { get; set; }
    }
}
